title: John Weatherall
email: j.f.weatherall.com
description: >
  Research, open source, field notes, and personal projects.

baseurl: ""
url: "https://johnwez1.github.io"

github_username: johnwez1

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty

header_pages:
  - about.md
  - research.md
  - open-source.md
  - personal.md
  - contact.md
